anneal_strategy: cos
backbone_layers:
- 2
- 3
- 7
batchsize: 10
betas:
- 0.9
- 0.999
bos_token: 1
channels: 1
config: /kaggle/working/LaTeX-ViT/checkpoints_vit/PureViT/config.yaml
data: pix2tex/model/dataset/weai_train.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
device: cuda
dim: 256
div_factor: 12
encoder_depth: 4
encoder_structure: vit
eos_token: 2
epoch: 2
epochs: 6
eps: 1.0e-08
final_div_factor: 100
gamma: 0.9995
gpu_devices:
- 0
- 1
heads: 8
id: 1twn1qku
load_chkpt: /kaggle/working/PureViT/PureViT_e03_step7995.pth
lr: 0.0005
lr_step: 30
max_dimensions:
- 896
- 384
max_height: 384
max_lr: 0.0005
max_seq_len: 512
max_width: 896
min_dimensions:
- 32
- 32
min_height: 32
min_width: 32
model_path: checkpoints_vit
name: PureViT
no_cuda: false
num_layers: 4
num_tokens: 8000
optimizer: AdamW
output_path: outputs
pad: false
pad_token: 0
patch_size: 16
pct_start: 0.25
resume: false
sample_freq: 2000
save_freq: 1
scheduler: OneCycleLR
seed: 42
temperature: 0.2
test_samples: 10
testbatchsize: 500
testdata: pix2tex/model/dataset/weai_test.pkl
tokenizer: pix2tex/model/dataset/weai_tokenizer.json
valbatches: 90
valdata: pix2tex/model/dataset/weai_valid.pkl
wandb: true
weight_decay: 0.01
