backbone_layers:
- 2
- 3
- 7
batchsize: 10
betas:
- 0.9
- 0.999
bos_token: 1
channels: 1
data: pix2tex/model/dataset/weai_train.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
device: cuda
dim: 256
encoder_depth: 4
encoder_structure: hybrid
eos_token: 2
epochs: 4
gamma: 0.9995
gpu_devices:
- 0
id: null
load_chkpt: null
lr_step: 30
max_dimensions:
- 992
- 496
max_height: 496
max_seq_len: 512
max_width: 992
min_dimensions:
- 32
- 32
min_height: 32
min_width: 32
model_path: checkpoints_vit
name: ViT-SingleGPU
no_cuda: false
num_layers: 4
num_tokens: 8000
optimizer: AdamW
output_path: outputs
pad: false
pad_token: 0
patch_size: 16
resume: true
sample_freq: 2000
save_freq: 1
scheduler: OneCycleLR 
seed: 42
temperature: 0.2
test_samples: 20
testbatchsize: 1000
testdata: pix2tex/model/dataset/weai_test.pkl
tokenizer: pix2tex/model/dataset/weai_tokenizer.json
valbatches: 100
valdata: pix2tex/model/dataset/weai_valid.pkl
wandb: true

#AdamW
lr: 0.0001
eps: 0.00000001
weight_decay: 0.01

#OneCycleLR
max_lr: 0.0005
pct_start: 0.25
anneal_strategy: cos
div_factor: 12
final_div_factor: 100