backbone_layers:
- 2
- 3
- 7
batchsize: 10
betas:
- 0.9
- 0.999
bos_token: 1
channels: 1
data: /content/drive/MyDrive/LaTeX-OCR/pix2tex/dataset/data/weai_train.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
device: cuda:0
dim: 256
encoder_depth: 4
encoder_structure: hybrid
eos_token: 2
epochs: 80
gamma: 0.9995
gpu_devices:
- 0
heads: 8
id: im2latex_weai_ver4
load_chkpt: null
lr: 0.001
lr_step: 30
max_dimensions:
- 992 
- 496
max_height: 496
max_seq_len: 512
max_width: 992
min_dimensions:
- 32
- 32
min_height: 32
min_width: 32
model_path: checkpoints
name: im2latex_weai_ver4
no_cuda: false
num_layers: 4
num_tokens: 8000
optimizer: AdamW
output_path: outputs
pad: false
pad_token: 0
patch_size: 16
sample_freq: 2000
save_freq: 1
scheduler: StepLR
seed: 42
temperature: 0.2
test_samples: 20
testdata: /content/drive/MyDrive/LaTeX-OCR/pix2tex/dataset/data/weai_test.pkl
testbatchsize: 1000
tokenizer: pix2tex/model/dataset/weai_tokenizer.json
valbatches: 100
valdata: /content/drive/MyDrive/LaTeX-OCR/pix2tex/dataset/data/weai_valid.pkl
weight_decay: 0.01
wandb: true
